services:
  ray-head:
    image: rayproject/ray:2.55.1-py312
    container_name: ray-head
    ports:
      - "${DASHBOARDPORT}:${DASHBOARDPORT}"
      - "${HEADNODEPORT}:${HEADNODEPORT}"
      - "${REDISPORT}:${REDISPORT}"
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    shm_size: 4g
    command: >
      bash -c "ray start --head 
      --port=${REDISPORT} 
      --dashboard-port=${DASHBOARDPORT} 
      --dashboard-host=0.0.0.0 
      --ray-client-server-port=${HEADNODEPORT} 
      --redis-password=${REDISPASSWORD} 
      --block"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2g'
    networks:
      - ray_net

  ray-worker:
    image: rayproject/ray:2.55.1-py312
    container_name: ray-worker
    depends_on:
      - ray-head
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    shm_size: 4g
    command: >
      bash -c "ray start 
      --address=ray-head:${REDISPORT} 
      --redis-password=${REDISPASSWORD} 
      --num-cpus=${NUM_CPU_WORKER} 
      --block"
    deploy:
      mode: replicated
      replicas: ${NUM_WORKERS}
      resources:
        limits:
          cpus: '3'
          memory: '6g'
    networks:
      - ray_net

networks:
  ray_net:
    ipam:
      driver: default
      config:
        - subnet: 172.63.0.0/16